version: 2
jobs:
  build:
    docker:
      - image: centos:7

    steps:
      - checkout

      - run:
          name: install centos-release-scl
          command: yum install -y centos-release-scl
      - run:
          name: install rust, cargo
	  command: yum install -y rust-toolset-7
      - run:
          name: start using software collections
	  command: scl enable rust-toolset-7 bash
      - run:
          name: Print the Current Time
          command: date