version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.31
    steps:
      - checkout
      - run:
          name: Build tcp_comms
          command: cargo build --verbose
      - run:
          name: Test tcp_comms
          command: ./test.sh